- name: ansible group account
  group:
    name: ansible
  become: yes

- name: ansible user account
  user:
    name: ansible
    comment: "Ansible Deployer"
    password: "*"
    group: ansible
  become: yes

- name: sudo without password for ansible
  copy:
    content: "ansible ALL=(ALL:ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/050_ansible-nopasswd
    mode: 0440
    validate: /usr/sbin/visudo -csf %s
  become: yes

- name: setup authorized keys for ansible user
  authorized_key:
    user: ansible
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdhl//Vd+2b+CDBKP8JL8cPJZN5Uxaw08g5x3vXnlmepy7EqH8rbNIm4ts5dM986ox6jQ1100hqFSRMdGmDphW6s42+dhoOrFMuUo7GRpGcD4EAytAbApGZLmNeAXTTx6f88X2kGUFvcwv9Ncs1AimKVbhaUOeeW4DX9SNodsVi+oJpJNPbs/1uJbQiHlp1gLNEL5hBwckxqNjw/Q5sbANR+YBI0DkkF72OTP//3BtKNzRuVL0MTcQg7h41wGImIS5mir5aZiDo9QJfr/hkBr43z8AY78Iix1TB/qqAQfmk1fKLnpexXYvh6BaYowhCGjgx/nU4ygROBPiePMqtJ4iNP+3fQSUPkjhe6ii//OPbCz70+luyziES2LQrEj8aedrZhdjMZ/HdjRigTY+quhwXmuRffUEMDqFJ8dg0EqAl7itbtkKCH2OyvEj6Vc8XCCmpkQ49YkyPsTunzi/y7faN0/0f3tDBTWW5zAWxbFmthML+TW5JKOxfkf/hfCg+ec= james@fractal"
  become: yes
