- name: install mopidy with plugins
  package:
    name:
      - mopidy
      - mopidy-mpd
      - gstreamer1.0-plugins-bad
      - python3-pip
    state: latest
  notify: "Restart mopidy"

- name: install mopidy python packages
  pip:
    name:
      - mopidy-jellyfin
      - mopidy-iris
    state: latest
  notify: "Restart mopidy"

- name: setup ram cache
  file:
    path: /var/run/mopidy
    state: directory
    owner: mopidy
    group: audio
    mode: "0755"
  notify: "Restart mopidy"

- name: install mopidy config
  template:
    src: templates/mopidy.conf.j2
    dest: /etc/mopidy/mopidy.conf
    owner: mopidy
    group: root
    mode: "0640"
  notify: "Restart mopidy"
