telegraf_agent_version: "1.22.1"
telegraf_agent_package_method: repo
telegraf_agent_hostname: "{{ ansible_hostname }}"
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = [ "http://nexus:8086" ]
        database = "telegraf-hosts"
        username = "{{ lowsec.influxdb.telegraf.user }}"
        password = "{{ lowsec.influxdb.telegraf.password }}"
