telegraf_agent_hostname: "{{ ansible_hostname }}"
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = [ "http://nexus:8086" ]
        database = "telegraf-hosts"
        username = "telegraf"
        password = "@PASSWORD@"
