#!/usr/bin/env fish
# deploy <host-name> [root@<target-host>]:
#  Builds the flake for host-name locally and deploys to target-host

set host $argv[1]
set target $argv[2]
set domain home.arpa

if [ -z "$target" ]
  set target "root@$host.$domain"
end

# Build flake locally, push to $host.
echo "Building $host and pushing to $target..."
nixos-rebuild \
  --flake ".#$host" \
  --target-host $target \
  --build-host localhost switch

# Log host & git commit.
set commit (git log -n 1 --format="[%ci] %h %s")
printf "%-12s %s\n" $host $commit >> log.txt
