#!/bin/sh
# deploy <host-name> [root@<target-host>]:
#  Builds the flake for host-name locally and deploys to target-host

host="$1"
target="$2"
domain="home.arpa"

if [ -z "$target" ]; then
  target="root@$host.$domain"
fi

# Build locally, push to $host.
nixos-rebuild --flake ".#$host" --target-host "$target" \
  --build-host localhost switch

# Log host & git commit.
commit="$(git log -n 1 --format="[%ci] %h %s")"
printf "%-12s %s\n" "$host" "$commit" >> log.txt
