#!/usr/bin/env fish

if test -n "$argv[1]"
  set host $argv[1]
end
if test -z "$host"
  echo "host env or argument required" >&2
  exit 1
end

set target "root@$host.home.arpa"

echo "Restarting $host"

ssh $target "reboot"
