#!/usr/bin/env fish

if test -n "$argv[1]"
  set host $argv[1]
end
if test -z "$host"
  echo "host env or argument required" >&2
  exit 1
end

set target "root@$host.home.arpa"

echo "Status for $host"

ssh $target "set -x; systemctl --failed; uname -a; uptime; df -h -x tmpfs -x overlay" 2>&1 \
  | sed -E -e "s/^(\+ .*)/\n$(set_color -r)\1$(set_color normal)/"
