all:
  children:
    # Mopidy nodes
    mopidy:
      hosts:
        theater-mopidy.dyn.home.arpa:
          ansible_host: 192.168.1.200
    # OctoPi nodes
    octopis:
      hosts:
        octopi.home.arpa:
    # Pis running Raspbian
    raspbian:
      children:
        mopidy:
        octopis:
    # Nodes monitored with telegraf
    telegraf:
      children:
        raspbian:
    # Nodes forwarding syslogs
    rsyslog_fwd:
      children:
        raspbian:
