all:
  children:
    # OctoPi nodes
    octopis:
      hosts:
        octopi.skynet.local:
    # Pis running Raspbian
    raspbian:
      children:
        octopis:
    # Nodes monitored with telegraf
    telegraf:
      children:
        raspbian:
    # Nodes forwarding syslogs
    rsyslog_fwd:
      children:
        raspbian:
