- hosts: all
  roles: [ common ]
  tags: [ common ]

- hosts: rsyslog_fwd
  vars_files:
    - lowsec.yml
  roles:
    - { role: robertdebock.rsyslog, become: yes }
  tags: [ rsyslog ]

- hosts: telegraf
  vars_files:
    - lowsec.yml
  roles:
    - dj-wasabi.telegraf
  tags: [ telegraf ]

- hosts: mopidy
  vars_files:
    - lowsec.yml
  roles:
    - { role: mopidy, become: yes }
  tags: [ mopidy ]
