- hosts: all
  roles: [ common ]
  tags: [ common ]

- hosts: rsyslog_fwd
  vars_files:
    - lowsec.yml
  roles:
    - { role: robertdebock.rsyslog, become: yes }

- hosts: telegraf
  vars_files:
    - lowsec.yml
  roles:
    - dj-wasabi.telegraf
