substitutions:
  device_name: family_esp32

esphome:
  name: ${device_name}
  platform: ESP32
  board: mhetesp32devkit

wifi:
  ssid: !secret 'wifi_ssid'
  password: !secret 'wifi_pass'
  domain: .skynet.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret 'wifi_pass'

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret 'api_pass'

ota:
  password: !secret 'ota_pass'

esp32_ble_tracker:

sensor:
  - platform: uptime
    name: "${device_name} Uptime Sensor"

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:1B:55:C5"
    temperature:
      name: "Dining Mi Temperature"
    humidity:
      name: "Dining Mi Humidity"
    battery_level:
      name: "Dining Mi Battery Level"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:C2:FA:A2"
    temperature:
      name: "Garage Mi Temperature"
    humidity:
      name: "Garage Mi Humidity"
    battery_level:
      name: "Garage Mi Battery Level"
