substitutions:
  device_name: family_esp32

sensor:
  - platform: uptime
    name: "${device_name} Uptime Sensor"

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:1B:55:C5"
    temperature:
      name: "Dining Mi Temperature"
    humidity:
      name: "Dining Mi Humidity"
    battery_level:
      name: "Dining Mi Battery Level"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:C2:FA:A2"
    temperature:
      name: "Garage Mi Temperature"
    humidity:
      name: "Garage Mi Humidity"
    battery_level:
      name: "Garage Mi Battery Level"

<<: !include base/mhet-devkit-ble.yaml
