substitutions:
  device_name: office_esp32

esphome:
  name: ${device_name}
  platform: ESP32
  board: mhetesp32devkit

wifi:
  ssid: !secret 'wifi_ssid'
  password: !secret 'wifi_pass'
  domain: .dyn.skynet.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret 'wifi_pass'

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret 'api_pass'

ota:
  password: !secret 'ota_pass'

esp32_ble_tracker:

sensor:
  - platform: uptime
    name: "${device_name} Uptime Sensor"

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:0F:5D:64"
    temperature:
      name: "Master Mi Temperature"
    humidity:
      name: "Master Mi Humidity"
    battery_level:
      name: "Master Mi Battery Level"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:F0:22:38"
    temperature:
      name: "Office Mi Temperature"
    humidity:
      name: "Office Mi Humidity"
    battery_level:
      name: "Office Mi Battery Level"
