substitutions:
  device_name: office_esp32

sensor:
  - platform: uptime
    name: "${device_name} Uptime Sensor"

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:0F:5D:64"
    temperature:
      name: "Master Mi Temperature"
    humidity:
      name: "Master Mi Humidity"
    battery_level:
      name: "Master Mi Battery Level"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:F0:22:38"
    temperature:
      name: "Office Mi Temperature"
    humidity:
      name: "Office Mi Humidity"
    battery_level:
      name: "Office Mi Battery Level"

<<: !include base/mhet-devkit-ble.yaml
